spring:
  application:
    name: smilex-boot
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true


# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: top.zsmile.**.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml


# smilex-config
smilex:
  server:
    workerId: 1
    dataCenterId: 1
